"""Initial migration with broker-neutral models

Revision ID: c3b7ef577438
Revises: 
Create Date: 2026-03-18 15:15:50.459968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b7ef577438'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('eventlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('broker', sa.Enum('SHIOAJI', 'IBKR', name='broker'), nullable=True),
    sa.Column('broker_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventlog_event_type'), 'eventlog', ['event_type'], unique=False)
    op.create_index(op.f('ix_eventlog_user_id'), 'eventlog', ['user_id'], unique=False)
    op.create_table('paperorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.Enum('SHIOAJI', 'IBKR', name='broker'), nullable=False),
    sa.Column('broker_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('broker_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('normalized_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sa.Enum('BUY', 'SELL', name='action'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Enum('LMT', 'MKT', name='ordertype'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED', name='orderstatus'), nullable=False),
    sa.Column('execution_mode', sa.Enum('PAPER', 'LIVE', name='executionmode'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paperorder_broker_order_id'), 'paperorder', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_paperorder_normalized_symbol'), 'paperorder', ['normalized_symbol'], unique=False)
    op.create_index(op.f('ix_paperorder_user_id'), 'paperorder', ['user_id'], unique=False)
    op.create_table('paperposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.Enum('SHIOAJI', 'IBKR', name='broker'), nullable=False),
    sa.Column('broker_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paperposition_normalized_symbol'), 'paperposition', ['normalized_symbol'], unique=False)
    op.create_index(op.f('ix_paperposition_user_id'), 'paperposition', ['user_id'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.Enum('SHIOAJI', 'IBKR', name='broker'), nullable=False),
    sa.Column('symbol_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instrument_type', sa.Enum('STOCK', 'FUTURES', 'OPTIONS', name='instrumenttype'), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_normalized_symbol'), 'watchlist', ['normalized_symbol'], unique=False)
    op.create_index(op.f('ix_watchlist_user_id'), 'watchlist', ['user_id'], unique=False)
    op.create_table('paperfill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.Enum('SHIOAJI', 'IBKR', name='broker'), nullable=False),
    sa.Column('broker_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['paperorder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paperfill_normalized_symbol'), 'paperfill', ['normalized_symbol'], unique=False)
    op.create_index(op.f('ix_paperfill_order_id'), 'paperfill', ['order_id'], unique=False)
    op.create_index(op.f('ix_paperfill_user_id'), 'paperfill', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paperfill_user_id'), table_name='paperfill')
    op.drop_index(op.f('ix_paperfill_order_id'), table_name='paperfill')
    op.drop_index(op.f('ix_paperfill_normalized_symbol'), table_name='paperfill')
    op.drop_table('paperfill')
    op.drop_index(op.f('ix_watchlist_user_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_normalized_symbol'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_paperposition_user_id'), table_name='paperposition')
    op.drop_index(op.f('ix_paperposition_normalized_symbol'), table_name='paperposition')
    op.drop_table('paperposition')
    op.drop_index(op.f('ix_paperorder_user_id'), table_name='paperorder')
    op.drop_index(op.f('ix_paperorder_normalized_symbol'), table_name='paperorder')
    op.drop_index(op.f('ix_paperorder_broker_order_id'), table_name='paperorder')
    op.drop_table('paperorder')
    op.drop_index(op.f('ix_eventlog_user_id'), table_name='eventlog')
    op.drop_index(op.f('ix_eventlog_event_type'), table_name='eventlog')
    op.drop_table('eventlog')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
